import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { HttpClient, HttpHeaders, HttpParams } from '@angular/common/http';
import { AuthService } from '../../../core/services/auth.service';
import { SharedSidebarComponent } from '../../shared/shared-sidebar/shared-sidebar.component';
import { ReportExportService } from '../../../core/services/report-export.service';
@Component({ selector: 'app-team-statistics', standalone: true, imports: [CommonModule, FormsModule, SharedSidebarComponent], templateUrl: './team-statistics.component.html', styleUrls: ['./team-statistics.component.scss'] })
export class TeamStatisticsComponent implements OnInit { start = ''; end = ''; data: any = { members: [] }; isExportOpen = false; constructor(private http: HttpClient, private auth: AuthService, private reportExport: ReportExportService) {} ngOnInit(): void { this.load(); } load(): void { let params = new HttpParams(); if (this.start) params = params.set('start_date', this.start); if (this.end) params = params.set('end_date', this.end); this.http.get<any>('http://localhost:8080/api/v1/manager/team/statistics', { params, headers: this.headers() }).subscribe({ next: data => this.data = data }); } toggleExportDropdown(): void { this.isExportOpen = !this.isExportOpen; } private rows(): unknown[][] { return (this.data.members || []).map((member: any) => [member.Name, member.Hadir, member.Terlambat, member.Total]); } exportCSV(): void { this.isExportOpen = false; this.reportExport.downloadCsv('statistik-kehadiran-tim.csv', ['Anggota', 'Hadir', 'Terlambat', 'Total'], this.rows()); } exportExcel(): void { this.isExportOpen = false; this.reportExport.downloadExcel('statistik-kehadiran-tim.xls', ['Anggota', 'Hadir', 'Terlambat', 'Total'], this.rows()); } exportJSON(): void { this.isExportOpen = false; this.reportExport.downloadJson('statistik-kehadiran-tim.json', this.data); } exportPDF(): void { this.isExportOpen = false; this.reportExport.print(); } private headers(): HttpHeaders { return new HttpHeaders().set('Authorization', `Bearer ${this.auth.getToken()}`); } }
