import { Component, OnDestroy, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { HttpClient, HttpHeaders, HttpParams } from '@angular/common/http';
import { AuthService } from '../../../core/services/auth.service';
import { SharedSidebarComponent } from '../../shared/shared-sidebar/shared-sidebar.component';
import { ReportExportService } from '../../../core/services/report-export.service';
import { NotificationService } from '../../../core/services/notification.service';

interface AttendanceMember { Name: string; Hadir: number; Terlambat: number; IzinCuti: number; Alpha: number; BelumAbsen: number; TotalHariKerja: number; TotalHariWajib?: number; PersentaseKehadiran: number; Total?: number; hadirPercentage: number; terlambatPercentage: number; izinCutiPercentage: number; alphaPercentage: number; belumAbsenPercentage: number; manager_id?: number | null; manager_name?: string; }
interface ManagerGroup { key: string; name: string; members: AttendanceMember[]; totalMembers: number; hadir: number; terlambat: number; izinCuti: number; alpha: number; belumAbsen: number; totalHariKerja: number; }

@Component({ selector: 'app-team-statistics', standalone: true, imports: [CommonModule, FormsModule, SharedSidebarComponent], templateUrl: './team-statistics.component.html', styleUrls: ['./team-statistics.component.scss'] })
export class TeamStatisticsComponent implements OnInit, OnDestroy {
  start = ''; end = ''; data: { members: AttendanceMember[] } = { members: [] }; isExportOpen = false; expandedManagers: Record<string, boolean> = {}; managerGroups: ManagerGroup[] = [];
  private disconnectRealtime?: () => void; private refreshTimer?: ReturnType<typeof setInterval>; private refreshTimerHandle?: ReturnType<typeof setTimeout>; private requestSequence = 0; private requestInFlight = false;
  loading = false; error = '';
  constructor(private http: HttpClient, private auth: AuthService, private reportExport: ReportExportService, private notificationService: NotificationService) {}
  ngOnInit(): void { this.load(); this.disconnectRealtime = this.notificationService.connectRealtime(() => this.scheduleRealtimeRefresh()); this.refreshTimer = setInterval(() => this.load(true), 30_000); }
  ngOnDestroy(): void { if (this.refreshTimer) clearInterval(this.refreshTimer); if (this.refreshTimerHandle) clearTimeout(this.refreshTimerHandle); this.disconnectRealtime?.(); }
  private scheduleRealtimeRefresh(): void { if (this.refreshTimerHandle) return; this.refreshTimerHandle = setTimeout(() => { this.refreshTimerHandle = undefined; this.load(true); }, 250); }
  load(background = false): void { if (this.requestInFlight && background) return; const sequence = ++this.requestSequence; this.requestInFlight = true; this.loading = !background; this.error = ''; let params = new HttpParams(); if (this.start) params = params.set('start_date', this.start); if (this.end) params = params.set('end_date', this.end); this.http.get<{ members: AttendanceMember[] }>('http://localhost:8080/api/v1/manager/team/statistics', { params, headers: this.headers() }).subscribe({ next: data => { if (sequence !== this.requestSequence) return; this.data = data || { members: [] }; this.managerGroups = this.buildManagerGroups(this.data.members); this.expandedManagers = {}; this.loading = false; this.requestInFlight = false; }, error: error => { if (sequence !== this.requestSequence) return; this.error = error?.error?.error || 'Statistik gagal dimuat.'; this.loading = false; this.requestInFlight = false; } }); }
  private buildManagerGroups(members: AttendanceMember[]): ManagerGroup[] { const groups = new Map<string, ManagerGroup>(); for (const rawMember of members || []) { const total = Number(rawMember.TotalHariKerja ?? rawMember.Total ?? 0); const percent = (value: number) => total ? value / total * 100 : 0; const member = { ...rawMember, hadirPercentage: percent(Number(rawMember.Hadir || 0)), terlambatPercentage: percent(Number(rawMember.Terlambat || 0)), izinCutiPercentage: percent(Number(rawMember.IzinCuti || 0)), alphaPercentage: percent(Number(rawMember.Alpha || 0)), belumAbsenPercentage: percent(Number(rawMember.BelumAbsen || 0)) }; const name = member.manager_name?.trim() || 'Belum Ada Manajer'; const managerId = member.manager_id; const key = managerId !== null && managerId !== undefined && String(managerId).trim() !== '' ? `manager-${managerId}` : 'unassigned'; let group = groups.get(key); if (!group) { group = { key, name, members: [], totalMembers: 0, hadir: 0, terlambat: 0, izinCuti: 0, alpha: 0, belumAbsen: 0, totalHariKerja: 0 }; groups.set(key, group); } group.members.push(member); group.totalMembers++; group.hadir += Number(member.Hadir || 0); group.terlambat += Number(member.Terlambat || 0); group.izinCuti += Number(member.IzinCuti || 0); group.alpha += Number(member.Alpha || 0); group.belumAbsen += Number(member.BelumAbsen || 0); group.totalHariKerja += total; } return Array.from(groups.values()); }
  get showManagerControls(): boolean { return this.managerGroups.length > 1; }
  isExpanded(key: string): boolean { return this.expandedManagers[key] === true; }
  toggleManager(key: string): void { this.expandedManagers = { ...this.expandedManagers, [key]: !this.isExpanded(key) }; }
  expandAll(): void { this.expandedManagers = Object.fromEntries(this.managerGroups.map(group => [group.key, true])); }
  collapseAll(): void { this.expandedManagers = {}; }
  percentage(hadir: number, total: number): number { return total ? Math.round((Number(hadir || 0) / total) * 100) : 0; }
  attendancePercentage(member: AttendanceMember): number { return Number(member.PersentaseKehadiran ?? this.percentage(Number(member.Hadir || 0) + Number(member.Terlambat || 0), Number(member.TotalHariKerja ?? member.Total ?? 0))); }
  toggleExportDropdown(): void { this.isExportOpen = !this.isExportOpen; }
  private exportRows(): unknown[][] { return this.managerGroups.flatMap(group => [[`Manajer: ${group.name}`, '', '', '', '', '', '', ''], ...group.members.map(member => [group.name, member.Name || '-', member.Hadir || 0, member.Terlambat || 0, member.IzinCuti || 0, member.Alpha || 0, member.BelumAbsen || 0, member.TotalHariKerja ?? member.Total ?? 0, this.attendancePercentage(member)] )]); }
  private printableRows(): unknown[][] { return this.managerGroups.flatMap(group => [[`${group.name} (${group.totalMembers} anggota)`, '', '', '', '', '', '', '', ''], ...group.members.map(member => [group.name, member.Name || '-', member.Hadir || 0, member.Terlambat || 0, member.IzinCuti || 0, member.Alpha || 0, member.BelumAbsen || 0, member.TotalHariKerja ?? member.Total ?? 0, `${this.attendancePercentage(member)}%`])]); }
  exportCSV(): void { this.isExportOpen = false; this.reportExport.downloadCsv('statistik-kehadiran-tim.csv', ['Manajer', 'Anggota', 'Hadir', 'Terlambat', 'Izin/Cuti', 'Alpha', 'Belum Absen', 'Total Hari Kerja', 'Persentase'], this.exportRows()); }
  exportExcel(): void { this.isExportOpen = false; this.reportExport.downloadExcel('statistik-kehadiran-tim.xls', ['Manajer', 'Anggota', 'Hadir', 'Terlambat', 'Izin/Cuti', 'Alpha', 'Belum Absen', 'Total Hari Kerja', 'Persentase'], this.exportRows()); }
  exportJSON(): void { this.isExportOpen = false; this.reportExport.downloadJson('statistik-kehadiran-tim.json', this.data); }
  exportPDF(): void { this.isExportOpen = false; void this.reportExport.downloadPdf('statistik-kehadiran-tim.pdf', 'Statistik Kehadiran Tim', this.periodLabel(), ['MANAJER', 'ANGGOTA', 'HADIR', 'TERLAMBAT', 'IZIN/CUTI', 'ALPHA', 'BELUM ABSEN', 'TOTAL HARI KERJA', 'PERSENTASE'], this.printableRows()); }
  printReport(): void { this.isExportOpen = false; this.reportExport.printReport('Statistik Kehadiran Tim', this.periodLabel(), ['MANAJER', 'ANGGOTA', 'HADIR', 'TERLAMBAT', 'IZIN/CUTI', 'ALPHA', 'BELUM ABSEN', 'TOTAL HARI KERJA', 'PERSENTASE'], this.printableRows()); }
  private periodLabel(): string { return this.start || this.end ? `${this.start || '-'} s/d ${this.end || '-'}` : new Intl.DateTimeFormat('id-ID', { day: '2-digit', month: 'long', year: 'numeric' }).format(new Date()); }
  private headers(): HttpHeaders { return new HttpHeaders().set('Authorization', `Bearer ${this.auth.getToken()}`); }
}
