import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { HttpClient, HttpHeaders, HttpParams } from '@angular/common/http';
import { AuthService } from '../../../core/services/auth.service';
import { SharedSidebarComponent } from '../../shared/shared-sidebar/shared-sidebar.component';
import { ReportExportService } from '../../../core/services/report-export.service';
@Component({ selector: 'app-intern-statistics', standalone: true, imports: [CommonModule, FormsModule, SharedSidebarComponent], templateUrl: './intern-statistics.component.html', styleUrls: ['./intern-statistics.component.scss'] })
export class InternStatisticsComponent implements OnInit { stats: any = { hadir: 0, izin_disetujui: 0 }; start = ''; end = ''; isExportOpen = false; constructor(private http: HttpClient, private auth: AuthService, private reportExport: ReportExportService) {} ngOnInit(): void { this.load(); } load(): void { let params = new HttpParams(); if (this.start) params = params.set('start_date', this.start); if (this.end) params = params.set('end_date', this.end); this.http.get<any>('http://localhost:8080/api/v1/internship/statistics', { params, headers: new HttpHeaders().set('Authorization', `Bearer ${this.auth.getToken()}`) }).subscribe({ next: data => this.stats = data }); } toggleExportDropdown(): void { this.isExportOpen = !this.isExportOpen; } exportCSV(): void { this.isExportOpen = false; this.reportExport.downloadCsv('statistik-kehadiran.csv', ['Metrik', 'Nilai'], [['Hadir', this.stats.hadir], ['Izin Disetujui', this.stats.izin_disetujui]]); } exportExcel(): void { this.isExportOpen = false; this.reportExport.downloadExcel('statistik-kehadiran.xls', ['Metrik', 'Nilai'], [['Hadir', this.stats.hadir], ['Izin Disetujui', this.stats.izin_disetujui]]); } exportJSON(): void { this.isExportOpen = false; this.reportExport.downloadJson('statistik-kehadiran.json', this.stats); } exportPDF(): void { this.isExportOpen = false; this.reportExport.print(); } }
