import { Component, OnInit } from '@angular/core';
import { CommonModule, DatePipe } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { HttpClient, HttpHeaders, HttpParams } from '@angular/common/http';
import { AuthService } from '../../../core/services/auth.service';
import { SharedSidebarComponent } from '../../shared/shared-sidebar/shared-sidebar.component';
import { ReportExportService } from '../../../core/services/report-export.service';
@Component({ selector: 'app-team-reports', standalone: true, imports: [CommonModule, FormsModule, DatePipe, SharedSidebarComponent], templateUrl: './team-reports.component.html', styleUrls: ['./team-reports.component.scss'] })
export class TeamReportsComponent implements OnInit { start = ''; end = ''; search = ''; reports: any[] = []; error = ''; isExportOpen = false; constructor(private http: HttpClient, private auth: AuthService, private reportExport: ReportExportService) {} ngOnInit(): void { this.load(); } load(): void { let params = new HttpParams(); if (this.start) params = params.set('start_date', this.start); if (this.end) params = params.set('end_date', this.end); if (this.search) params = params.set('search', this.search); this.http.get<any[]>('http://localhost:8080/api/v1/manager/team/reports', { params, headers: this.headers() }).subscribe({ next: data => this.reports = data || [], error: e => this.error = e.error?.error || 'Gagal memuat laporan tim' }); } toggleExportDropdown(): void { this.isExportOpen = !this.isExportOpen; } exportCSV(): void { this.isExportOpen = false; this.reportExport.downloadCsv('laporan-tim.csv', ['Tanggal', 'Anggota', 'Tugas', 'Kegiatan', 'Status'], this.reports.map(row => [row.Tanggal, row.Employee?.User?.Nama, row.Tugas, row.DeskripsiKegiatan, row.StatusLogbook])); } exportExcel(): void { this.isExportOpen = false; this.reportExport.downloadExcel('laporan-tim.xls', ['Tanggal', 'Anggota', 'Tugas', 'Kegiatan', 'Status'], this.reports.map(row => [row.Tanggal, row.Employee?.User?.Nama, row.Tugas, row.DeskripsiKegiatan, row.StatusLogbook])); } exportJSON(): void { this.isExportOpen = false; this.reportExport.downloadJson('laporan-tim.json', this.reports); } exportPDF(): void { this.isExportOpen = false; this.reportExport.print(); } private headers(): HttpHeaders { return new HttpHeaders().set('Authorization', `Bearer ${this.auth.getToken()}`); } }
